### ISSUE TITLE
demo image tags appear to be missing from DockerHub

### ISSUE THREAD

**Issue by edtan** [cyriltovena/observability-nomad#8]
It looks like the `:demo` image tags are missing from DockerHub now.  For example:
```
docker run --rm -it prom/prometheus:demo 
Unable to find image 'prom/prometheus:demo' locally
docker: Error response from daemon: manifest for prom/prometheus:demo not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

These images are referenced in the following nomad jobs:
* https://github.com/cyriltovena/observability-nomad/blob/main/jobs/01-prometheus.nomad.hcl#L57
* https://github.com/cyriltovena/observability-nomad/blob/main/jobs/05-tempo.nomad.hcl#L42
* https://github.com/cyriltovena/observability-nomad/blob/main/jobs/15-tns.nomad.hcl#L41
* https://github.com/cyriltovena/observability-nomad/blob/main/jobs/21-promtail.nomad.hcl#L72

It seems like these work if you remove the `:demo` tag.  (I did not test `tns` in my setup though, so it's possible that might still be working.)

Thanks for this repo and the presentation, I learned a lot!

**Comment by cyriltovena** [comment]
Sorry for the late response and thank you for the kind word.

@obourdon Recently worked on this I believe it was for preloading in the vm the images with a tag demo.

So the demo tag only work within the machine of vagrant.

**Comment by edtan** [comment]
Oops, I completely missed that in the Vagrantfile.  Thanks for the reply!

**Comment by obourdon** [comment]
@edtan deeply sorry about the confusion induced by [this fix](https://github.com/cyriltovena/observability-nomad/commit/ef49947be74c10e34047ee1f68541e7a99eb852e)
